version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.23.3

jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go mod download
      - run:
          name: Perform style checks
          command: |
            go vet ./...
      - run:
          name: Run tests
          command:  go test -v ./...
